{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dify-postgresql
  namespace: {{ .Values.postgresql.namespace }}
  labels:
    demo.redhat.com/application: "dify-enterprise"
type: Opaque
stringData:
  database: {{ .Values.postgresql.database | quote }}
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
